# Generated by Django 3.1.7 on 2021-03-31 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.CharField(blank=True, max_length=32, null=True)),
                ('comments', models.CharField(blank=True, max_length=32, null=True)),
                ('shares', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_post_url', models.CharField(max_length=100)),
                ('task_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('link', models.CharField(blank=True, max_length=1024, null=True)),
                ('sex', models.CharField(blank=True, max_length=8, null=True)),
                ('city_of_birth', models.CharField(blank=True, max_length=128, null=True)),
                ('current_city', models.CharField(blank=True, max_length=128, null=True)),
                ('birthday', models.CharField(blank=True, max_length=128, null=True)),
                ('fb_id', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('last_time_updated', models.DateField(auto_now=True)),
                ('fb_post_id', models.CharField(blank=True, max_length=1024, null=True)),
                ('fb_repost_id', models.CharField(blank=True, max_length=128, null=True)),
                ('fb_repost_link', models.CharField(blank=True, max_length=2048, null=True)),
                ('fb_post_link', models.CharField(blank=True, max_length=1024, null=True)),
                ('fb_post_link_likes', models.CharField(blank=True, max_length=1024, null=True)),
                ('content_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.content')),
                ('stat_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.poststat')),
                ('task_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.task')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
    ]
