# Generated by Django 3.1.7 on 2021-04-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('login', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('available', models.BooleanField(default=True)),
                ('last_time_checked', models.DateField(auto_now=True)),
                ('attempts', models.IntegerField(default=0)),
                ('expirationDate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='posturl',
            name='added_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='posturl',
            name='is_parsing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posturl',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posturl',
            name='is_successful',
            field=models.BooleanField(default=True),
        ),
    ]
