# Generated by Django 3.1.7 on 2021-04-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210401_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content_id',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='stat_id',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='task_id',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='content',
            name='text',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
