# Generated by Django 3.1.7 on 2021-04-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210401_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='expirationDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='last_time_checked',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
